### ISSUE TITLE
Accessories states in Home App does not update when controlled manually 

### ISSUE THREAD

**Issue by pete913** [homebridge/HAP-NodeJS#1002]
### Current Situation

I have noticed that when I create a bridge accessory the bridged accessories does not update its states on Apple Home app. I am able to control the light from Home app but when the light is manually controlled it does not reflect the status on Home app. But when we close and open the Apple Home app the accessory retrieves the current state of light. I have noticed that Hap is closing the http connection when publishing the accessory in bridge mode. The http connection is alive for one to two secs and during this period the states update. And as soon as the http connection is closed the states stop to reflect in Home app. Then again need to close and open the home app to retrieve the current correct state.

But when I create a accessory rather than creating a bridge the states are updated flawlessly manually as well as from Home app.
I have used a updateValue() method to update state.
please need help  here.

### Logs

```markdown
HAP-NodeJS:EventedHTTPServer Currently 0 hap connections open:  +12s
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'REQUEST'              (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16) +19s
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'AUTHENTICATED'        (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16) +10ms
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'CLOSED'               (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16) +3ms
  HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.34] New connection from client on interface eth0 (::ffff:192.168.1.41) +7s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Internal HTTP server listening on 127.0.0.1:33059 +13s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Internal HTTP socket connected. HAPConnection now fully set up! +5ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /pair-verify +2ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: POST /pair-verify +18s
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Pair verify step 1/2 +3ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +118ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /pair-verify +20ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: POST /pair-verify +134ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Pair verify step 2/2 +2ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Client 523AD553-C777-4854-B5D1-1F6CF096339D verification complete +75ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +83ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /accessories +13ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: GET /accessories +20ms
GET function
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +10ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /characteristics?id=2.10 +23ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: GET /characteristics?id=2.10 +33ms
GET function
  HAP-NodeJS:Accessory [Infiware 5BF0] Got Characteristic "On" value: "0" +19s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +6ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /characteristics +10ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: PUT /characteristics +16ms
  HAP-NodeJS:Accessory [Infiware 5BF0] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"ev":true}]} +15ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.34] Registered Characteristic "On" on "Infiware 5BF0" for events +1ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +5ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Client connection closed +5s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP connection was closed +3ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP server was closed +1ms
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'REQUEST'              (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16) +21s
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'AUTHENTICATED'        (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16) +3ms
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'CLOSED'               (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16) +4ms
  HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.34] New connection from client on interface eth0 (::ffff:192.168.1.41) +21s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Internal HTTP server listening on 127.0.0.1:46801 +16s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Internal HTTP socket connected. HAPConnection now fully set up! +5ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /pair-verify +2ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: POST /pair-verify +21s
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Pair verify step 1/2 +2ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +112ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /pair-verify +12ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: POST /pair-verify +122ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Pair verify step 2/2 +1ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Client 523AD553-C777-4854-B5D1-1F6CF096339D verification complete +72ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +77ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /accessories +9ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: GET /accessories +12ms
GET function
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +14ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /characteristics?id=2.10 +10ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: GET /characteristics?id=2.10 +25ms
GET function
  HAP-NodeJS:Accessory [Infiware 5BF0] Got Characteristic "On" value: "0" +21s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +5ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /characteristics +6ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: PUT /characteristics +10ms
  HAP-NodeJS:Accessory [Infiware 5BF0] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"ev":true}]} +9ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.34] Registered Characteristic "On" on "Infiware 5BF0" for events +1ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +4ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Client connection closed +5s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP connection was closed +4ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP server was closed +2ms
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'REQUEST'              (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16) +7s
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'AUTHENTICATED'        (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16) +3ms
  HAP-NodeJS:EventEmitter [::ffff:192.168.1.34] Registered event 'CLOSED'               (total: 1)                  at EventedHTTPServer.onConnection (/usr/local/bin/11iot-server/iot-server/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16) +3ms
  HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.34] New connection from client on interface eth0 (::ffff:192.168.1.41) +7s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Internal HTTP server listening on 127.0.0.1:33713 +2s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Internal HTTP socket connected. HAPConnection now fully set up! +6ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /pair-verify +2ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: POST /pair-verify +7s
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Pair verify step 1/2 +3ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +112ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /pair-verify +16ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: POST /pair-verify +126ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Pair verify step 2/2 +1ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] Client 523AD553-C777-4854-B5D1-1F6CF096339D verification complete +79ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +103ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /accessories +16ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: GET /accessories +38ms
GET function
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +15ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /characteristics +16ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: PUT /characteristics +31ms
  HAP-NodeJS:Accessory [Infiware 5BF0] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"value":1}]} +7s

  HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.34] Muting event '2.10' notification for this connection since it originated here. +297ms
  HAP-NodeJS:Accessory [Infiware 5BF0] Setting Characteristic "On" to value 1 +11ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +14ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /characteristics +6ms
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: PUT /characteristics +20ms
  HAP-NodeJS:Accessory [Infiware 5BF0] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"ev":true}]} +9ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.34] Registered Characteristic "On" on "Infiware 5BF0" for events +1ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +4ms

  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP request: /characteristics +2s
  HAP-NodeJS:HAPServer [54:52:00:cc:b3:c5] HAP Request: PUT /characteristics +2s
  HAP-NodeJS:Accessory [Infiware 5BF0] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"value":0}]} +2s
  HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.34] Muting event '2.10' notification for this connection since it originated here. +2s
  HAP-NodeJS:Accessory [Infiware 5BF0] Setting Characteristic "On" to value 0 +7ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP Response is finished +13ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] Client connection closed +5s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP connection was closed +3ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.34] HTTP server was closed +2ms
  HAP-NodeJS:EventedHTTPServer Currently 0 hap connections open:  +22s
```

### Configuration

```json
NA
```

### Environment

- OS: Raspberry Bulls eye
- Node:16.20.0
- npm: 9.6.3
- Hap.js: 0.11.0

### Process Supervisor

systemd

**Comment by pete913** [comment]
has anyone faced similar kind of issues..

**Comment by pete913** [comment]
I have noticed that only bridged accessories does not update status but in case of single accessory status are updated and connections remains open. @NorthernMan54

**Comment by NorthernMan54** [comment]
I had made a very long post the other day, but I think I forgot to hit enter

This is from my homebridge-tasmota plugin, demonstrating event notifications working correctly.  This is from within homebridge, so it is a bridged accessory.

```
Opening the Home App to the Room with the device

  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP request: /characteristics +9s
  HAP-NodeJS:HAPServer [AA:BB:CC:DD:EE:02] HAP Request: PUT /characteristics +9s
  HAP-NodeJS:Accessory [Heisenberg 1F10] Processing characteristic set: {"characteristics":[{"aid":4,"iid":10,"ev":true},{"aid":4,"iid":11,"ev":true},{"aid":4,"iid":14,"ev":true}]} +0ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "On" on "Heisenberg 1F10" for events +1ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "Configured Name" on "Heisenberg 1F10" for events +1ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "Outlet In Use" on "Heisenberg 1F10" for events +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP Response is finished +5ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP request: /characteristics +4ms
  HAP-NodeJS:HAPServer [AA:BB:CC:DD:EE:02] HAP Request: PUT /characteristics +9ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Processing characteristic set: {"characteristics":[{"aid":5,"iid":10,"ev":true},{"aid":5,"iid":11,"ev":true},{"aid":5,"iid":14,"ev":true},{"aid":5,"iid":15,"ev":true},{"aid":5,"iid":16,"ev":true}]} +6ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "On" on "Heisenberg 1F10" for events +0ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "Configured Name" on "Heisenberg 1F10" for events +0ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "On" on "Heisenberg 1F10" for events +0ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "Rotation Speed" on "Heisenberg 1F10" for events +0ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.62] Registered Characteristic "Configured Name" on "Heisenberg 1F10" for events +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP Response is finished +2ms

Home App Requesting Status of Devices

  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP request: /characteristics?id=4.10,5.10,5.14,5.15 +129ms
  HAP-NodeJS:HAPServer [AA:BB:CC:DD:EE:02] HAP Request: GET /characteristics?id=4.10,5.10,5.14,5.15 +132ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "1" +132ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "0" +0ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "0" +0ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "Rotation Speed" value: "0" +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP Response is finished +4ms

Local Control of the accessory

  Tasmota:mqtt emit tasmota_F52066/tele/STATE {"Time":"2023-04-11T23:46:24","Uptime":"1T03:58:09","UptimeSec":100689,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":2,"SSId":"The_Beach","BSSId":"20:C9:D0:1A:CA:85","Channel":1,"Mode":"11n","RSSI":56,"Signal":-72,"LinkCount":1,"Downtime":"0T00:00:06"}} +19s
  Tasmota:switch MQTT tasmota_F52066/tele/STATE {"Time":"2023-04-11T23:46:24","Uptime":"1T03:58:09","UptimeSec":100689,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":2,"SSId":"The_Beach","BSSId":"20:C9:D0:1A:CA:85","Channel":1,"Mode":"11n","RSSI":56,"Signal":-72,"LinkCount":1,"Downtime":"0T00:00:06"}} +0ms
[Tasmota] Updating 'Washer Power:On' to false

Homebridge sending event notification of change in status

  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] Sending HAP event notifications [ { aid: 4, iid: 10, value: 0 } ] +14s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP request: /characteristics?id=4.10,5.14,5.15,5.10 +1s
  HAP-NodeJS:HAPServer [AA:BB:CC:DD:EE:02] HAP Request: GET /characteristics?id=4.10,5.14,5.15,5.10 +15s
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "0" +15s
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "0" +0ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "Rotation Speed" value: "0" +0ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "0" +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP Response is finished +3ms

Local Control of the accessory

  Tasmota:mqtt emit tasmota_F52066/tele/STATE {"Time":"2023-04-11T23:46:29","Uptime":"1T03:58:14","UptimeSec":100694,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER":"ON","Wifi":{"AP":2,"SSId":"The_Beach","BSSId":"20:C9:D0:1A:CA:85","Channel":1,"Mode":"11n","RSSI":50,"Signal":-75,"LinkCount":1,"Downtime":"0T00:00:06"}} +5s
  Tasmota:switch MQTT tasmota_F52066/tele/STATE {"Time":"2023-04-11T23:46:29","Uptime":"1T03:58:14","UptimeSec":100694,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER":"ON","Wifi":{"AP":2,"SSId":"The_Beach","BSSId":"20:C9:D0:1A:CA:85","Channel":1,"Mode":"11n","RSSI":50,"Signal":-75,"LinkCount":1,"Downtime":"0T00:00:06"}} +5s
[Tasmota] Updating 'Washer Power:On' to true

Homebridge sending event notification of change in status

  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] Sending HAP event notifications [ { aid: 4, iid: 10, value: 1 } ] +4s
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP request: /characteristics?id=4.10,5.15,5.14,5.10 +1s
  HAP-NodeJS:HAPServer [AA:BB:CC:DD:EE:02] HAP Request: GET /characteristics?id=4.10,5.15,5.14,5.10 +5s
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "1" +5s
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "Rotation Speed" value: "0" +0ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "0" +0ms
  HAP-NodeJS:Accessory [Heisenberg 1F10] Got Characteristic "On" value: "0" +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.62] HTTP Response is finished +3ms
```

**Comment by pete913** [comment]
This is how I publish Homebridge bridge accessory
`class HomeBridgeService {

    constructor(userName, pincode, deviceList = []) {
        this.deviceList = deviceList
        this.userName = userName
        this.pincode = pincode
        // this.setupId = setupId
        this.bridgeAccessory = new Accessory("Infiware Bridge Accessory", hap.uuid.generate("Infiware bridge"))
        this.bridgeAccessory._isBridge = true
        this.addBridgedAccessories()
        this.publishAccessories()
    }


    addBridgedAccessories = () => {
        this.accessories = this.createAccessories()
        this.bridgeAccessory.addBridgedAccessories(this.accessories.map(accessory => accessory.getAccessory()))
    }

    createAccessories = () => {
        return this.deviceList.map(device => this.createAccessory(device))
    }

    createAccessory = (device) => {
        switch (device.type) {
            case 'light':
                return new LightBulbAccessory(device.name, device.uuid, device.attribute, ['dim', 'ramp'].includes(device.attribute), false)
            case 'rgbLight':
                return new LightBulbAccessory(device.name, device.uuid,'rgbLight', true, true)
            case 'fan':
                return new FanAccessory(device.name, device.uuid, device.attribute)
            case 'shutter':
                return new WindowCoveringAccessory(device.name, device.uuid, device.attribute)
             case 'AC':
            case 'ACIntesis':
                return new HVACAccessory(device.name, device.uuid, device.attribute)
        }
    }

    publishAccessories = () => this.bridgeAccessory.publish({
        username: this.userName,
        pincode: this.pincode,
        // setupID:this.setupId,
        port: 47219,
        category: this.bridgeAccessory.category
    })

    setAccessoryState = (deviceId, type, status) => {
        const accessory = this.accessories.find(accessory1 => accessory1.uuid == deviceId)
        if(accessory==undefined||accessory==null) {return}
        switch (accessory.type) {
            case 'light':
                // const attrib = type == 'switch' ? value ? 'ON' : 'OFF' : 'RAMP'
                accessory.setAccessoryState(type, status)
                break
            case 'rgbLight':
                const rgbLightAttrib = ''
                accessory.setAccessoryState(rgbLightAttrib, status)
                break
            case 'fan':
                const fanAttrib = ''
                accessory.setAccessoryState(fanAttrib, status)
                break
            case 'shutter':
                const shutterAttrib = ''
                accessory.setAccessoryState(shutterAttrib, status)
                break
            case 'AC':
            case 'ACIntesis':
                accessory.setAccessoryState(type, status)
                break

        }

    }
}`

**Comment by ebaauw** [comment]
Make sure to power-cycle your home hub(s), especially when on the new HomeKit architecture.  Under the old architecture, each Apple device running HomeKit would connect to each accessory (or bridge) directly, under the new architecture, the Apple devices only connect through the home hub.  So for changes, the accessory (through Homebridge) notifies the home hub, and the home hub notifies the HomeKit on your phone.

**Comment by pete913** [comment]
when I publish single accessory I get updates without closing and opening the Homekit app.Only in case of bridge accessory I am unable to get the status.

**Comment by NorthernMan54** [comment]
Pls share a link to your GitHub repo.

**Comment by mrjackyliang** [comment]
This looks like the same exact issue that I'm having.

https://github.com/homebridge/homebridge/issues/3529
