### ISSUE TITLE
error /home/pi/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56 

### ISSUE THREAD

**Issue by Keoni80** [homebridge/HAP-NodeJS#211]
Hi,, i have an error when i run node Core.js:

pi@raspberrypi:~/HAP-NodeJS $ sudo node Core.js
**\* WARNING **\* The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs
**\* WARNING **\* The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
Parsing accessory: desktop_light_accessory.js
Parsing accessory: light_accessory.js
/home/pi/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/home/pi/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement](/home/pi/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/home/pi/HAP-NodeJS/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/pi/HAP-NodeJS/lib/Accessory.js:465:20)
    at emitNone (events.js:67:13)
    at HAPServer.emit (events.js:166:7)
    at HAPServer._onListening (/home/pi/HAP-NodeJS/lib/HAPServer.js:169:8)
    at emitNone (events.js:67:13)
    at EventedHTTPServer.emit (events.js:166:7)
pi@raspberrypi:~/HAP-NodeJS $ 

any idea?,, thanks

**Comment by jamesabruce** [comment]
See my comment at bottom: https://github.com/KhaosT/HAP-NodeJS/issues/139

**Comment by chabad360** [comment]
This did not fix the issue for me
