### ISSUE TITLE
Having duplicate accessory names causes error

### ISSUE THREAD

**Issue by hansmbakker** [homebridge/HAP-NodeJS#244]
**What I did:**
- Installed homebridge & hue plugin
- Set up bridge ip in config.json, registered username in config.json
- Paired with phone
- Changed lamp names I named two lamps the same ("Ceiling") since they are in different rooms -> I wanted to say something like "hey Siri, turn on the ceiling lamp in the bedroom" instead of naming the lamps "ceiling bedroom" and "ceiling hall".

**Result:** homebridge+hue plugin crashes after a restart

**Workaround:** renaming one of the "ceiling" lamps to "ceiling bedroom" so that the names are not duplicate anymore helped

**Cause:** UUID is generated based upon the accessory name in https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/util/uuid.js like in https://github.com/nfarina/homebridge/blob/620c8473b86fe21fe473b18894e6ca592caeb13b/example-plugins/homebridge-samplePlatform/index.js#L183

**Possible solutions:** 
- the "name" should be a concatenation of accessory name and room name to make them unique per room (fix in nfarina/homebridge)
- this UUID shouldn't be linked to the name but to the lamp ID (lamp zigbee address) so that the UUID is unique (fix in homebridge-philipshue)
- the UUID should be not based on a hash which makes it predictable (fix in HAP-NodeJS)

**Log:**

```
[2016-05-14 20:18:01] Loaded plugin: homebridge-philipshue
[2016-05-14 20:18:01] Registering platform 'homebridge-philipshue.PhilipsHue'
[2016-05-14 20:18:01] ---
[2016-05-14 20:18:01] Loaded config.json with 0 accessories and 1 platforms.
[2016-05-14 20:18:01] ---
[2016-05-14 20:18:01] Loading 1 platforms...
[2016-05-14 20:18:01] [Philips Hue] Initializing PhilipsHue platform...
[2016-05-14 20:18:01] [Philips Hue] PhilipsHue Platform Plugin Version 0.0.2
[2016-05-14 20:18:01] [Philips Hue] Fetching Philips Hue lights...
[2016-05-14 20:18:01] [Philips Hue] Initializing platform accessory 'Ceiling'...
[2016-05-14 20:18:01] [Philips Hue] Initializing platform accessory 'Ceiling'...
/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 88c675f0-a405-4b4e-b2e6-1ad5e94d45c1
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:219:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:346:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-philipshue/index.js:140:9
    at resolveValue (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/node-hue-api/hue-api/utils.js:34:13)
    at _fulfilled (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/l
```

**Comment by hansmbakker** [comment]
@donavanbecker is this solved?

**Comment by ebaauw** [comment]
> this UUID shouldn't be linked to the name but to the lamp ID (lamp zigbee address) so that the UUID is unique (fix in homebridge-philipshue)

That's the only right solution.  You might try homebridge-hue instead, that bases the UUID on the `uniqueid` attribute (whose value is derived from the Zigbee mac address and endpoint of the light).

**Comment by hansmbakker** [comment]
thank you @ebaauw!

**Comment by Supereg** [comment]
I don't know what have been done in the homebridge code base since you opened your issue. Currently you cannot add multiple Accessories with the same UUID to a bridge. HAP-NodeJS uses the UUID to uniquely identify an Accessory and thus all data is associated with this UUID. One of the things are accessory ids and instance ids, which are used by HomeKit to uniquely identify accessories and services and characteristics. So if you expose two accessories with the same UUID on a bridge this will lead to unexpected behavior and collisions of accessory ids and instance ids and thus will cause problems on the HomeKit side.
Anybody using the HAP-NodeJS library should ensure unique UUIDs are used and that the data they are derived from is also unique in some way.
HAP-NodeJS prevents accessories with the same uuid get added to a bridge, so I think there is already prevention installed that your described issue should not occur anymore.
