### ISSUE TITLE
Crash in HAPServer.js

### ISSUE THREAD

**Issue by FluBBaOfWard** [homebridge/HAP-NodeJS#271]
This just happened yesterday, from out of the blue and now it won't start again.
Running on OS X 10.11.6, iOS 10 beta 3 on both iPhone and AppleTV.

/opt/OpenHAB-HomeKit-Bridge/node_modules/hap-nodejs/lib/HAPServer.js:490
var sequence = objects[HAPServer.Types.SEQUENCE_NUM][0]; // value is single byte with sequence number
^

TypeError: Cannot read property '0' of undefined
at HAPServer._handlePairVerify (/opt/OpenHAB-HomeKit-Bridge/node_modules/hap-nodejs/lib/HAPServer.js:490:55)
at HAPServer. (/opt/OpenHAB-HomeKit-Bridge/node_modules/hap-nodejs/lib/HAPServer.js:201:39)
at emitNone (events.js:67:13)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:921:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)

**Comment by KhaosT** [comment]
Looks like iOS sent something unexpected ... If possible, can you try remove persist folder, remove accessory from iOS device and re-pair again?

**Comment by FluBBaOfWard** [comment]
Yeah, I know I can probably get it going by removing the persist folder and so.
I was just hoping I could be of some help if you wanted to test some code on my install as is, maybe just a better error description and not crashing?
