### ISSUE TITLE
Streaming issue

### ISSUE THREAD

**Issue by abataille** [homebridge/HAP-NodeJS#307]
After successfully having run foscam-camera streaming over a couple of days today it crashed with the following error at the api.

...
Thu, 13 Oct 2016 07:36:22 GMT StreamController 
Session: 
ControllerAddress: 192.xxx.xxx.53 
VideoPort: 64154 
AudioPort: 52448 
Video Crypto: 2 
Video Master Key: 
Video Master Salt: 
Audio Crypto: 2 
Audio Master Key: 
Audio Master Salt: 
Thu, 13 Oct 2016 07:36:22 GMT rtsp-stream start-line sent SETUP rtsp://192.168.178.21:88/videoMain/track1 RTSP/1.0
Thu, 13 Oct 2016 07:36:22 GMT rtsp-stream headers sent { Transport: 'RTP/AVP;unicast;client_port=10000-10001',
CSeq: 3,
Authorization: 'Digest username="xx", realm="Foscam IPCam Living Video", nonce="564ee45d32c0933144238e5e8ee1161f", uri="rtsp://192.xxx.xxx.21:88/videoMain/track1", response="13748afdd8dd7099ae00d00b8f4a8cb8",' }
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream decoding chunk 'RTSP/1.0 200 OK\r\nCSeq: 3\r\nDate: Thu, Oct 13 2016 07:36:31 GMT\r\nTransport: RTP/AVP;unicast;destination=192.xxx.xxx.55;source=192.xxx.xxx.21;client_port=10000-10001;server_port=6970-6971\r\nSession: 660EFFB5;timeout=65\r\n\r\n'
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start of header
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream end of header
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start-line sent SETUP rtsp://192.168.178.21:88/videoMain/track2 RTSP/1.0
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream headers sent { Transport: 'RTP/AVP;unicast;client_port=10006-10007',
CSeq: 4,
Authorization: 'Digest username="xx", realm="Foscam IPCam Living Video", nonce="564ee45d32c0933144238e5e8ee1161f", uri="rtsp://192.xxx.xxx.21:88/videoMain/track2", response="8dae190336204dffaa44b6bfde7d6323",',
Session: '660EFFB5' }
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream decoding chunk 'RTSP/1.0 200 OK\r\nCSeq: 4\r\nDate: Thu, Oct 13 2016 07:36:32 GMT\r\nTransport: RTP/AVP;unicast;destination=192.xxx.xxx.55;source=192.xxx.xxx.21;client_port=10006-10007;server_port=6972-6973\r\nSession: 660EFFB5;timeout=65\r\n\r\n'
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start of header
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream end of header
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAxsBAQACDjE5Mi4xNjguMTc4LjUzAwKa+gQC4MwEBwIAAwABAQIFBwIAAwABAQI="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAxsBAQACDjE5Mi4xNjguMTc4LjUzAwKa+gQC4MwEBwIAAwABAQIFBwIAAwABAQI="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] HTTP Response is finished
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] HTTP request: /characteristics?id=1.22
Thu, 13 Oct 2016 07:36:23 GMT HAPServer [E2:CD:13:7C:9E:FA] HAP Request: GET /characteristics?id=1.22
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Getting value for Characteristic "Setup Endpoints"
Thu, 13 Oct 2016 07:36:23 GMT StreamController Setup Read
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Got Characteristic "Setup Endpoints" value: ARANDdqKc2lLlqcf+UZhYglQAgEAAxsBAQACDjE5Mi4xNjguMTc4LjU1AwISJwQCGCcEBwEBAgIAAwAFBwEBAgIAAwAGBAc74cwHBKJZqy8=
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAgEAAxsBAQACDjE5Mi4xNjguMTc4LjU1AwISJwQCGCcEBwEBAgIAAwAFBwEBAgIAAwAGBAc74cwHBKJZqy8="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAgEAAxsBAQACDjE5Mi4xNjguMTc4LjU1AwISJwQCGCcEBwEBAgIAAwAFBwEBAgIAAwAGBAc74cwHBKJZqy8="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] HTTP Response is finished
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] HTTP request: /characteristics
Thu, 13 Oct 2016 07:36:23 GMT HAPServer [E2:CD:13:7C:9E:FA] HAP Request: PUT /characteristics
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Processing characteristic set: [{"aid":1,"iid":20,"value":"ARUCAQABEA0N2opzaUuWpx/5RmFiCVA="}]
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Setting Characteristic "Selected Stream Configuration" to value ARUCAQABEA0N2opzaUuWpx/5RmFiCVA=
Thu, 13 Oct 2016 07:36:23 GMT StreamController Write SelectedStreamConfiguration
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start-line sent TEARDOWN rtsp://192.168.178.21:88/videoMain RTSP/1.0
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream headers sent { Session: '660EFFB5',
CSeq: 5,
Authorization: 'Digest username="xx", realm="Foscam IPCam Living Video", nonce="564ee45d32c0933144238e5e8ee1161f", uri="rtsp://192.xxx.xxx.21:88/videoMain", response="9cc4c22e78ea81ae74f8118163e0bf40",' }
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] HTTP Response is finished
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.xxx.xxx.53] HTTP request: /characteristics
Thu, 13 Oct 2016 07:36:23 GMT HAPServer [E2:CD:13:7C:9E:FA] HAP Request: PUT /characteristics
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Processing characteristic set: [{"aid":1,"iid":20,"value":null}]
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Setting Characteristic "Selected Stream Configuration" to value null
Thu, 13 Oct 2016 07:36:23 GMT StreamController Write SelectedStreamConfiguration
buffer.js:257
throw new TypeError(kFromErrorMsg);
^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
at fromObject (buffer.js:257:9)
at Function.Buffer.from (buffer.js:97:10)
at Buffer (buffer.js:76:17)
at StreamController._handleSelectedStreamConfigurationWrite (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:280:14)
at . (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:261:12)
at emitMany (events.js:127:13)
at emit (events.js:201:7)
at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
at Accessory. (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:727:22)
at Array.forEach (native)
at Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:672:8)
at emitMany (events.js:127:13)
at HAPServer.emit (events.js:201:7)
at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:966:10)
at HAPServer. (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:203:39)
at emitNone (events.js:86:13)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)

Any idea.

**Comment by KhaosT** [comment]
```
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Processing characteristic set: [{"aid":1,"iid":20,"value":null}]
```
HomeKit sent a null for this characteristic which is not expected value... Can you reliably reproduce this issue?

**Comment by abataille** [comment]
I don’t think so. I looped thru the log files and debug files since I used the streaming. This is the first time the issue happened.
From the time of day, there was practically no activity, but the cam may have detected a motion activity at that time.

**Comment by Samfox2** [comment]
I think it is reproduceable if you just disconnect the camera from the power source. I got the same issue after disconnecting...

**Comment by abataille** [comment]
I cannot confirm that.
I did the following:

- Look at the cam in the Home app.
- Disconnect the cam from Power.
- Try to get a stream in the Home app.
- Reconnect the cam.

The log as shown below showed errors, but different ones and Homebridge didn't crash (the ip address is that of the disconnected cam). After reconnect everything works fine

Oct 15 09:41:19 raspberrypi3 homebridge[14328]: Unhandled rejection RequestError: Error: connect EHOSTUNREACH 192.xxx.xxx.54:88
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at new RequestError (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request-promise/lib/errors.js:11:15)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request-promise/lib/rp.js:60:32)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at self.callback (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request/request.js:187:22)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at emitOne (events.js:96:13)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at Request.emit (events.js:188:7)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at Request.onRequestError (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request/request.js:813:8)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at emitOne (events.js:96:13)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at ClientRequest.emit (events.js:188:7)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at Socket.socketErrorListener (_http_client.js:308:9)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at emitOne (events.js:96:13)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at Socket.emit (events.js:188:7)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at emitErrorNT (net.js:1271:8)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
Oct 15 09:41:19 raspberrypi3 homebridge[14328]: at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Samfox2** [comment]
Hmm, in my case homebridge crashes after removing the plug (sometimes it works for a few minutes but it definitally crashes).

**Comment by Samfox2** [comment]
This is what I get:

Unhandled 'error' event:
Error: read EHOSTUNREACH

at TCP.onread (net.js:564:26)
