### ISSUE TITLE
HAP-NodeJS ISSUE on OpenWrt

### ISSUE THREAD

**Issue by cnliri1** [homebridge/HAP-NodeJS#366]
Tried node Core.js on OpenWrt 

reports error as below,the architecture is mips
if anyone success in openwrt?

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by imReker** [comment]
Cross compile dns_sd_bindings on PC.

[dns_sd_bindings.zip](https://github.com/KhaosT/HAP-NodeJS/files/1652229/dns_sd_bindings.zip) is the binary for MT7620A, put it in `node_modules/mdns/build/Release
`
