### ISSUE TITLE
"Node persist error"

### ISSUE THREAD

**Issue by majda107** [homebridge/HAP-NodeJS#493]
Hello, i am trying to install HAP-NodeJS on my RPi3. I am absolute begginer. When i try to start "Core.js" with "sudo node Core.js" it says this : 

pi@raspberrypi:~/HAP-NodeJS $ sudo node Core.js
module.js:491
    throw err;
    ^

Error: Cannot find module 'node-persist'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/Core.js:2:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

I have got node version v8.4.0.

 pi@raspberrypi:~ $ node -v
v8.4.0

Can anyone help me with this problem? I tried reinstalling node and other stuff.... Nothing is working for me :C

**Comment by pdlove** [comment]
In the Hap-nodejs folder, have you run the command ‘npm install’?

**Comment by majda107** [comment]
Also if I do this :

**Comment by majda107** [comment]
No, i will try it right now !

**Comment by majda107** [comment]
I thrown this : 

pi@raspberrypi:~/HAP-NodeJS $ npm install
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/fs'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-08-23T11_37_19_262Z-debug.log

:C

**Comment by majda107** [comment]
I closed thread by mistake huh sorry....

**Comment by KhaosT** [comment]
@majda107 Looks like a corrupted node install. Please try steps discussed in [this thread](https://github.com/nodejs/node/issues/9355) and see if it fix the npm install issue for you.
