### ISSUE TITLE
HAP-NodeJS Node persist error

### ISSUE THREAD

**Issue by majda107** [homebridge/HAP-NodeJS#494]
Hello, i am trying to install HAP-NodeJS on my RPi3. I am absolute begginer. When i try to start "Core.js" with "sudo node Core.js" it says this :

pi@raspberrypi:~/HAP-NodeJS $ sudo node Core.js
module.js:491
throw err;
^

Error: Cannot find module 'node-persist'
at Function.Module._resolveFilename (module.js:489:15)
at Function.Module._load (module.js:439:25)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
at Object. (/home/pi/HAP-NodeJS/Core.js:2:15)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)

I have got node version v8.4.0.

pi@raspberrypi:~ $ node -v
v8.4.0

Can anyone help me with this problem? I tried reinstalling node and other stuff.... Nothing is working for me :C

If I try to install npm in HAP folder, it gives me error too :C

**Comment by majda107** [comment]
! SOLVED !

I just downloaded Node 7 from this link : https://nodejs.org/dist/latest-v7.x/
and followed this : https://github.com/KhaosT/HAP-NodeJS/wiki/Installing guide
