### ISSUE TITLE
HELP! Windows 10 error

### ISSUE THREAD

**Issue by IFloppyPenguin** [homebridge/HAP-NodeJS#515]
Im running windows 10 and i get this 

C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dns_sd.cpp
  dns_service_browse.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_sd.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\build\dns_sd_bin
dings.vcxproj]
  dns_service_enumerate_domains.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_browse.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\buil
d\dns_sd_bindings.vcxproj]
  dns_service_get_addr_info.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_get_addr_info.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\md
ns\build\dns_sd_bindings.vcxproj]
  dns_service_process_result.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_enumerate_domains.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_module
s\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_process_result.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\m
dns\build\dns_sd_bindings.vcxproj]
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\build\d
ns_sd_bindings.vcxproj]
  dns_service_ref_deallocate.cpp
  dns_service_ref_sock_fd.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_deallocate.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\m
dns\build\dns_sd_bindings.vcxproj]
  dns_service_register.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_sock_fd.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns
\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_register.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\bu
ild\dns_sd_bindings.vcxproj]
  dns_service_update_record.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_resolve.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\bui
ld\dns_sd_bindings.vcxproj]
  mdns_utils.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_update_record.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\md
ns\build\dns_sd_bindings.vcxproj]
  network_interface.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\mdns_utils.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\build\dns_sd
_bindings.vcxproj]
  socket_watcher.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\network_interface.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\build
\dns_sd_bindings.vcxproj]
  txt_record_ref.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\socket_watcher.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\build\dn
s_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_ref.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\build\dn
s_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_create.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\build
\dns_sd_bindings.vcxproj]
  txt_record_set_value.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_deallocate.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
  txt_record_get_length.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_set_value.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\bu
ild\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_get_length.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
  win_delay_load_hook.cc
c:\users\user\downloads\hap-nodejs-master\hap-nodejs-master\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_buffer_to_object.cpp) [C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\Downloads\HAP-NodeJS-master\HAP-NodeJS-master\node_modules\mdns
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-10-16T20_05_54_012Z-debug.log

**Comment by IFloppyPenguin** [comment]
[2017-10-16T20_05_54_012Z-debug.log](https://github.com/KhaosT/HAP-NodeJS/files/1388957/2017-10-16T20_05_54_012Z-debug.log)


Thats the log
