### ISSUE TITLE
TypeError: PythonShell.run is not a function

### ISSUE THREAD

**Issue by New-GitHub** [homebridge/HAP-NodeJS#607]
**点击手机显示打开然后秒关闭。终端提示错误信息如下，求大神解答。**

```
root@raspberrypi:~# node HomeKitAppleDeveloper/Core.js 
HomeKit Apple Developer starting...
Change: true
/root/HomeKitAppleDeveloper/accessories/HomeKitAppleDeveloper_accessory.js:82
            PythonShell.run('../project/open.py', function (err) {
                        ^

TypeError: PythonShell.run is not a function
    at onUpdate (/root/HomeKitAppleDeveloper/accessories/HomeKitAppleDeveloper_accessory.js:82:25)
    at Characteristic.<anonymous> (/root/HomeKitAppleDeveloper/lib/AccessoryLoader.js:164:7)
    at Characteristic.emit (events.js:182:13)
    at Characteristic.setValue (/root/HomeKitAppleDeveloper/lib/Characteristic.js:320:10)
    at Accessory.<anonymous> (/root/HomeKitAppleDeveloper/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Accessory._handleSetCharacteristics (/root/HomeKitAppleDeveloper/lib/Accessory.js:811:8)
    at HAPServer.emit (events.js:182:13)
    at HAPServer._handleCharacteristics (/root/HomeKitAppleDeveloper/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/root/HomeKitAppleDeveloper/lib/HAPServer.js:209:39)
```

**Comment by TechMky** [comment]
I am getting this issue too, even though I am importing the module correctly.

**Comment by rajatrawataku1** [comment]
Do you guys any solution for it because I am also getting the same issue?

**Comment by planform** [comment]
use node-cmd

**Comment by Mukesh1412** [comment]
same issue iam getting

**Comment by cleek000** [comment]
Same issue "TypeError: PythonShell.run is not a function", any help is appreciated, thanks in advance!

**Comment by francovp** [comment]
Getting this after I update the package "python-shell" to version 1.0.6
Version 0.5.0 was my latest working version.
Maybe Issue related: https://github.com/extrabacon/python-shell/issues/156

**Comment by ykm11** [comment]
You guys probably tried such like
```
const PythonShell = require('python-shell')
PythonShell.run('/PATH/TO/example.py', null, function (err, results) {
  if (err) throw err;
  console.log('finished');
  console.log(results);
});
```

I got a same error, so I changed a little.

```
const ps = require('python-shell')
ps.PythonShell.run('/PATH/TO/example.py', null, function (err, results) {
  if (err) throw err;
  console.log('finished');
  console.log(results);
});
```

It works.

**Comment by moziahsv** [comment]
why does it work?

**Comment by philacher95** [comment]
@ykm11 ...... this works ....but folks the problem is I think from the python file Path:

for mine, I did not state the path correctly. 
Please check your .py file path
