### ISSUE TITLE
running camera core and then attempting to access it results in 

### ISSUE THREAD

**Issue by thales-man** [homebridge/HAP-NodeJS#709]
run: ts-node --files src/cameraCore.ts
HAP-NodeJS starting...
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

RPI 3, Pi cam v1.3, node 10.16.3, typescript 3.6.3, ts node 8.3.0
IOS 12.4.1 and home app

**Comment by codyc1515** [comment]
ENOENT = You need to install ffmpeg

**Comment by Shaquu** [comment]
I suggest to make a dry run for ffmpeg in terminal outside of HAP-NodeJS before you proceed.
