### ISSUE TITLE
Got this error after installing Hap NodeJs, how to solve . Thanks

### ISSUE THREAD

**Issue by Jacquesduval** [homebridge/HAP-NodeJS#791]
pi@raspberrypi:~ $ ts-node --files src/Core.ts
Error: Cannot find module '/home/pi/src/Core.ts'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:226:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:485:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by dunklesToast** [comment]
Have you cloned the repo via the `git clone` command? If so, you need to `cd` into the cloned directory. Try `cd hap-nodejs` and then `ts-node --files src/Core.ts`

**Comment by Jacquesduval** [comment]
Thanks a lot Tom. Will try it tomorrow. 
I am in France. 
Best Rgds 

Jacques Duval
Tél : +33 6 07 01 96 61

**Comment by n0rt0nthec4t** [comment]
I found the easiest way to install the current version of hap-nodes that uses typescript is just to do  **npm install hap-nodejs** 

Thats avoids all the hassles with typescript if just doing accessory development
