### ISSUE TITLE
TypeError: Class constructor Characteristic cannot be invoked without 'new' after upgrade to 0.7.0

### ISSUE THREAD

**Issue by marcoschmidt79** [homebridge/HAP-NodeJS#821]
Hello, i have a problem after upgrade to 0.7.0, any homebridge-plugins works not. i go back to 0.6.9 and the plugins works fine. what is the problem?

```
Mai 07 17:48:06 homebridge homebridge[8064]: [7.5.2020, 17:48:06] TypeError: Class constructor Characteristic cannot be invoked without 'new'
Mai 07 17:48:06 homebridge homebridge[8064]:     at new EvePowerConsumption (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:148:18)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Outlet.Service.addOptionalCharacteristic (/usr/local/lib/node_modules/hap-nodejs/src/lib/Service.ts:333:24)
Mai 07 17:48:06 homebridge homebridge[8064]:     at new MqttPowerConsumptionTasmotaAccessory (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:239:15)
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:356:50
Mai 07 17:48:06 homebridge homebridge[8064]:     at Array.forEach (<anonymous>)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:329:29)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:155:12)
Mai 07 17:48:06 homebridge homebridge[8064]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Module._compile (internal/modules/cjs/loader.js:1176:30)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Module.load (internal/modules/cjs/loader.js:1040:32)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Function.Module._load (internal/modules/cjs/loader.js:929:14)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Mai 07 17:48:06 homebridge homebridge[8064]:     at internal/main/run_main_module.js:17:47
Mai 07 17:48:06 homebridge homebridge[8064]: (node:8064) UnhandledPromiseRejectionWarning: TypeError: Class constructor Service cannot be invoked without 'new'
Mai 07 17:48:06 homebridge homebridge[8064]:     at new Service.SwitchProgram (/usr/local/lib/node_modules/homebridge-automation-switches/src/HomeKitTypes.js:42:15)
Mai 07 17:48:06 homebridge homebridge[8064]:     at SwitchAccessory.getSwitchProgramService (/usr/local/lib/node_modules/homebridge-automation-switches/src/AutomationSwitchAccessory.js:81:21)
Mai 07 17:48:06 homebridge homebridge[8064]:     at SwitchAccessory.createServices (/usr/local/lib/node_modules/homebridge-automation-switches/src/AutomationSwitchAccessory.js:48:12)
Mai 07 17:48:06 homebridge homebridge[8064]:     at new SwitchAccessory (/usr/local/lib/node_modules/homebridge-automation-switches/src/AutomationSwitchAccessory.js:31:27)
Mai 07 17:48:06 homebridge homebridge[8064]:     at AutomationSwitchesPlatform._createAutomationSwitch (/usr/local/lib/node_modules/homebridge-automation-switches/src/index.js:131:12)
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge-automation-switches/src/index.js:96:25
Mai 07 17:48:06 homebridge homebridge[8064]:     at Array.forEach (<anonymous>)
Mai 07 17:48:06 homebridge homebridge[8064]:     at AutomationSwitchesPlatform.accessories (/usr/local/lib/node_modules/homebridge-automation-switches/src/index.js:73:14)
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:414:24
Mai 07 17:48:06 homebridge homebridge[8064]:     at new Promise (<anonymous>)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:413:12)
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:401:28
Mai 07 17:48:06 homebridge homebridge[8064]:     at Array.forEach (<anonymous>)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
Mai 07 17:48:06 homebridge homebridge[8064]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 07 17:48:06 homebridge homebridge[8064]: (Use `node --trace-warnings ...` to show where the warning was created)
Mai 07 17:48:06 homebridge homebridge[8064]: (node:8064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Mai 07 17:48:06 homebridge homebridge[8064]: (node:8064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Mai 07 17:48:06 homebridge homebridge[8064]: (node:8064) UnhandledPromiseRejectionWarning: TypeError: Class constructor Service cannot be invoked without 'new'
Mai 07 17:48:06 homebridge homebridge[8064]:     at new Service.TelegramBot (/usr/local/lib/node_modules/homebridge-telegram/src/HomeKitTypes.js:25:15)
Mai 07 17:48:06 homebridge homebridge[8064]:     at BotAccessory.getBotService (/usr/local/lib/node_modules/homebridge-telegram/src/BotAccessory.js:66:24)
Mai 07 17:48:06 homebridge homebridge[8064]:     at BotAccessory.createServices (/usr/local/lib/node_modules/homebridge-telegram/src/BotAccessory.js:40:12)
Mai 07 17:48:06 homebridge homebridge[8064]:     at new BotAccessory (/usr/local/lib/node_modules/homebridge-telegram/src/BotAccessory.js:29:27)
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge-telegram/src/index.js:46:28
Mai 07 17:48:06 homebridge homebridge[8064]:     at Array.forEach (<anonymous>)
Mai 07 17:48:06 homebridge homebridge[8064]:     at TelegramPlatform.accessories (/usr/local/lib/node_modules/homebridge-telegram/src/index.js:43:10)
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:414:24
Mai 07 17:48:06 homebridge homebridge[8064]:     at new Promise (<anonymous>)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:413:12)
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:401:28
Mai 07 17:48:06 homebridge homebridge[8064]:     at Array.forEach (<anonymous>)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
Mai 07 17:48:06 homebridge homebridge[8064]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 07 17:48:06 homebridge homebridge[8064]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 07 17:48:06 homebridge homebridge[8064]: (node:8064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
Mai 07 17:48:06 homebridge homebridge[8064]: [7.5.2020, 17:48:06] TypeError: Cannot read property 'log' of undefined
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:77:17
Mai 07 17:48:06 homebridge homebridge[8064]:     at FSReqCallback.oncomplete (fs.js:163:23)
Mai 07 17:48:06 homebridge homebridge[8064]: [7.5.2020, 17:48:06] TypeError: Cannot read property 'log' of undefined
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:80:17
Mai 07 17:48:06 homebridge homebridge[8064]:     at FSReqCallback.oncomplete (fs.js:163:23)
Mai 07 17:48:06 homebridge homebridge[8064]: [7.5.2020, 17:48:06] TypeError: Cannot read property 'log' of undefined
Mai 07 17:48:06 homebridge homebridge[8064]:     at /usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:83:17
Mai 07 17:48:06 homebridge homebridge[8064]:     at FSReqCallback.oncomplete (fs.js:163:23)
Mai 07 17:48:06 homebridge homebridge[8064]: [7.5.2020, 17:48:06] Got SIGTERM, shutting down Homebridge...
```

**Comment by Supereg** [comment]
Are you running the latest homebridge beta or how did you install hap-nodejs when running hombridge. Since the latest homebridge release does not package 0.7.0 currently.

**Comment by marcoschmidt79** [comment]
i ve installed hap-nodejs with "npm install -g hap-nodejs" and update with npm-check. homebridge 1.0.4 is running.

**Comment by Supereg** [comment]
First of all it is not advised to run homebridge with a hap-nodejs version different from the prepackaged one.
Secondly the issue was mitigated by [v0.7.2](https://github.com/homebridge/HAP-NodeJS/releases/tag/v0.7.2) for now.

**Comment by marcoschmidt79** [comment]
0.7.2 works fine, thank you so much.
