### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by beckmx** [homebridge/HAP-NodeJS#84]
Hello guys, does anyone know why this issue is occurring? nodes -v v0.12.5

bookair-2:HAP-NodeJS myself$ node BridgedCore.js
HAP-NodeJS starting...
TCP server accepting connection on port: 51826
HAP Server is listening
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/Users/myself/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/myself/HAP-NodeJS/node_modules/mdns/lib/mdns_service.js:18:40)

**Comment by beckmx** [comment]
It looks I cannot make it work under MacOSX, any of you have managed to install under OS X? if so, what version?

I read in a couple of forums, the yosemite release has troubles with the discovery layer.
