### ISSUE TITLE
v0.10.3 breaks FLOAT characteristic with minStep of 0.01

### ISSUE THREAD

**Issue by ebaauw** [homebridge/HAP-NodeJS#971]
### Analysis

See https://github.com/ebaauw/homebridge-rpi/issues/143.  I'm getting:
> This plugin generated a warning from the characteristic 'Load': characteristic was supplied illegal value: number Infinity exceeded maximum of 1.7976931348623157e+308. See https://homebridge.io/w/JtMGR for more info.

When setting _Load_ to a valid value, like 0.12, 0.2, or 0.07.

The characteristic is defined with type `FLOAT` and `minStep` 0.01.  No `maxValue` nor `minValue`.  I don't recognise `Infinity`, nor the maximum value mentioned in the warning.

After manually reverting to v0.10.2, the warning is gone.

### Expected Behavior

Accept valid values, as v0.10.2.

### Steps To Reproduce

Re-install Homebridge, so it installs hap-nodejs@0.10.3.  Run Homebridge RPi.

### Logs

```markdown
[9/18/2022, 10:15:00 PM] [RPi] pi10: set Frequency from 800MHz to 700MHz
[9/18/2022, 10:15:00 PM] [RPi] pi10: set Load from 0.12 to 0.09
[9/18/2022, 10:15:00 PM] [homebridge-rpi] This plugin generated a warning from the characteristic 'Load': characteristic was supplied illegal value: number Infinity exceeded maximum of 1.7976931348623157e+308. See https://homebridge.io/w/JtMGR for more info.
[9/18/2022, 10:15:00 PM] [homebridge-rpi] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2138:105)
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:14)
    at Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at CharacteristicDelegate.set value [as value] (/Users/ebaauw/GitHub/homebridge-rpi/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:317:28)
    at Object.set (/Users/ebaauw/GitHub/homebridge-rpi/node_modules/homebridge-lib/lib/ServiceDelegate/index.js:256:50)
    at RpiService.checkState (/Users/ebaauw/GitHub/homebridge-rpi/lib/RpiService.js:111:22)
    at RpiAccessory.heartbeat (/Users/ebaauw/GitHub/homebridge-rpi/lib/RpiAccessory.js:306:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpiAccessory.<anonymous> (/Users/ebaauw/GitHub/homebridge-rpi/lib/RpiAccessory.js:231:11)
```

### Configuration

```json
n/a
```

### Environment

- OS: macOS Monterey 12.6.0 (21G115)
- Software: Homebridge v1.5.0 (HAP v0.10.3)
- Node: v16.17.0
- npm: 8.19.2

### Process Supervisor

not applicable

**Comment by ebaauw** [comment]
The warnings are also gone after defining `minValue` and `maxValue` properties.

**Comment by ebaauw** [comment]
Thanks, folks!
