### ISSUE TITLE
TypeError: crypto_1.default.getCiphers is not a function at Object../node_modules/hap-nodejs/dist/lib/util/hapCrypto.js

### ISSUE THREAD

**Issue by mandy-Tony** [homebridge/HAP-NodeJS#992]
### Current Situation

Hey, We are trying to use the Hap-nodejs in react interface for application sign-in, we have resolved many of errors but we are stuck at this error. 

### Logs

```markdown
Uncaught TypeError: crypto_1.default.getCiphers is not a function
    at Object../node_modules/hap-nodejs/dist/lib/util/hapCrypto.js (hapCrypto.ts:7:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/hap-nodejs/dist/lib/util/eventedhttp.js (eventedhttp.ts:11:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/hap-nodejs/dist/lib/HAPServer.js (HAPServer.ts:23:1)
    at Object.options.factory (react refresh:6:1)
```

### Configuration

```json
package.json
=================

{
  "name": "webkit",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "assert": "^2.0.0",
    "babel-eslint": "^10.1.0",
    "buffer": "^6.0.3",
    "child_process": "^1.0.2",
    "dgram": "^1.0.1",
    "hap-nodejs": "^0.11.0",
    "net": "^1.0.2",
    "os": "^0.1.2",
    "path": "^0.12.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "stream": "^0.0.2",
    "util": "^0.12.5",
    "web-vitals": "^2.1.4",
    "webpack": "^5.75.0"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "react-app-rewired": "^2.2.1"
  }
}

====================================================================
config-overrides.js
=======================

 
const webpack = require('webpack'); 
module.exports = function override(config) { 
		const fallback = config.resolve.fallback || {}; 
	// 	Object.assign(fallback, { 
    // 	"crypto": require.resolve("crypto-browserify"), 
    //   "stream": require.resolve("stream-browserify"), 
    //   "assert": require.resolve("assert"), 
    //   "http": require.resolve("stream-http"), 
    //   "https": require.resolve("https-browserify"), 
    //   "os": require.resolve("os-browserify"), 
    //   "url": require.resolve("url") ,
    //   "fs": require.resolve("fs") ,
    //   "dgram": require.resolve("dgram"),
    //   "child_process": require.resolve("child_process"),
    //   }) 
    Object.assign(fallback, { 
    	"crypto": false, 
      "stream": false, 
      "assert": false, 
      "http": false, 
      "https": false, 
      "timers": false, 
      "os": false, 
      "url": false,
      "fs":false ,
      "dgram": false,
      "child_process": false,
      }) 
   config.resolve.fallback = fallback; 
   config.plugins = (config.plugins || []).concat([ 
   	new webpack.ProvidePlugin({ 
    	process: 'process/browser', 
      Buffer: ['buffer', 'Buffer'] 
    }) 
   ]) 
   return config; }
```

### Environment

- OS: Windows 10
- Software: hap-nodejs
- Node: 16.13.0
- npm: 8.1..0

### Process Supervisor

not applicable

### Additional Context

![Capture](https://user-images.githubusercontent.com/120465479/207360090-5b52cc11-19d3-4063-a934-abe7b1e56797.PNG)

**Comment by Supereg** [comment]
This refers to line https://github.com/homebridge/HAP-NodeJS/blob/0655c18fc3ccc0637166ccfd915bf7aef0d2b14f/src/lib/util/hapCrypto.ts#L7

How does a react runtime differ from a regular nodejs runtime? Is the issue completely solved if you manually remove this line? It's just a sanity check of the environment so not mission critical for operation.

**Comment by mandy-Tony** [comment]
We are still getting the same error even after manually removing the lines

**Comment by Supereg** [comment]
> We are still getting the same error even after manually removing the lines

Could you attach the error trace with the respective line removed in the local JavaScript source file. The error is directly emitted from the line. If it is removed, the error should definitely change.

> How does a react runtime differ from a regular nodejs runtime?

To state previous question again. Given the react dependence, is this running inside a browser? Or is this using a standard nodejs environment (as indicated in the original post: nodejs 16.13.0). I'm very unfamiliar with development with react, so there seems to be a difference in the execution environment causing this error.
